cine/urls.py
    
from django.conf.urls import url
from django.urls import path, include

from .views import MovieList, MovieDetail, MovieCreation, MovieUpdate, MovieDelete
from .views import PersonList, PersonDetail, PersonCreation, PersonUpdate, PersonDelete
urlpatterns = [   
    url(r'^$', MovieList.as_view(), name='list'),
    
    url(r'^movies/$', MovieList.as_view(), name='list'),
    url(r'^movie/(?P<pk>\d+)$', MovieDetail.as_view(), name='detail'),
    url(r'^movie/new$', MovieCreation.as_view(), name='new'),
    url(r'^movie/edit/(?P<pk>\d+)$', MovieUpdate.as_view(), name='edit'),
    url(r'^movie/delete/(?P<pk>\d+)$', MovieDelete.as_view(), name='delete'),
    
    url(r'^persons/$', PersonList.as_view(), name='list_p'),
    url(r'^person/(?P<pk>\d+)$', PersonDetail.as_view(), name='detail_p'),
    url(r'^person/new$', PersonCreation.as_view(), name='new_p'),
    url(r'^person/edit/(?P<pk>\d+)$', PersonUpdate.as_view(), name='edit_p'),
    url(r'^person/delete/(?P<pk>\d+)$', PersonDelete.as_view(), name='delete_p'),
    path('accounts/', include('django.contrib.auth.urls')),
]

movieCompany/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .api import router
from cine import api_views as cine_views
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    url('api/v1/login', cine_views.login),
    path('docs/', include_docs_urls(title='Movies API')),
    url('', include(('cine.urls','cine'), namespace='cine')),
]

# app_name = 'cine'

cine/models.py
from django.db import models

class Person(models.Model):
    id = models.AutoField(auto_created = True,
                  primary_key = True,
                  serialize = True, 
                  verbose_name ='ID')
    last_name=models.CharField(max_length=100)
    first_name=models.CharField(max_length=100)
    aliases=models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.first_name + ' ' + self.last_name   

class Movie(models.Model):
    id = models.AutoField(auto_created = True,
                  primary_key = True,
                  serialize = True, 
                  verbose_name ='ID')
    title = models.CharField(max_length=100)
    release_year = models.PositiveSmallIntegerField()
    casting = models.ManyToManyField(Person, related_name="movies_as_char")
    directors = models.ManyToManyField(Person, related_name="movies_as_dir")
    producers = models.ManyToManyField(Person, related_name="movies_as_prod")

    def __str__(self):
        return self.title

cine/forms.py
from django import forms
from cine.models import Movie, Person
from django.db import models

class PersonMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.last_name + ' ' + obj.first_name

class MovieMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.title

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'release_year', 'casting', 'directors', 'producers']
    
    casting = PersonMultipleChoiceField(Person.objects.all(), widget=forms.CheckboxSelectMultiple)
    directors = PersonMultipleChoiceField(Person.objects.all(), widget=forms.CheckboxSelectMultiple)
    producers = PersonMultipleChoiceField(Person.objects.all(), widget=forms.CheckboxSelectMultiple)

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'aliases']

cine/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Movie, Person
from .forms import MovieForm, PersonForm
from django.contrib.auth.mixins import LoginRequiredMixin
class MovieList(ListView):
    model = Movie
    template_name = 'movies/movie_list.html'

class MovieDetail(DetailView):
    model = Movie
    template_name = 'movies/movie_detail.html'

class MovieCreation(LoginRequiredMixin, CreateView):
    model = Movie
    form_class = MovieForm
    template_name = 'movies/movie_form.html'
    success_url = reverse_lazy('cine:list')
class MovieUpdate(LoginRequiredMixin, UpdateView):
    model = Movie
    form_class = MovieForm
    template_name = 'movies/movie_form.html'
    success_url = reverse_lazy('cine:list')
class MovieDelete(LoginRequiredMixin, DeleteView):
    model = Movie
    template_name = 'movies/movie_confirmdelete.html'
    success_url = reverse_lazy('cine:list')


#PersonForm

class PersonList(ListView):
    model = Person
    template_name = 'persons/person_list.html'

class PersonDetail(DetailView):
    model = Person
    template_name = 'persons/person_detail.html'

class PersonCreation(LoginRequiredMixin, CreateView):
    model = Person
    form_class = PersonForm
    template_name = 'persons/person_form.html'
    success_url = reverse_lazy('cine:list_p')
class PersonUpdate(LoginRequiredMixin, UpdateView):
    model = Person
    form_class = PersonForm
    template_name = 'persons/person_form.html'
    success_url = reverse_lazy('cine:list_p')
class PersonDelete(LoginRequiredMixin, DeleteView):
    model = Person
    template_name = 'persons/person_confirmdelete.html'
    success_url = reverse_lazy('cine:list_p')

class Index(TemplateView):
    template_name = 'index.html'

cine/templates/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Movies Company</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12">
          <h2 class="mt-2">Movies Company</h2>
          <a href="{% url "cine:list" %}"><i class="ml-5 fas fa-users"></i>Movies</a>
          <a href="{% url "cine:list_p" %}"><i class="ml-5 fas fa-users"></i> Persons</a>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

cine/templates/movies/movie_confirmdelete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    Are you sure to delete the movie: "{{ object }}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cine/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block content %}
<h3>Movie:  {{ movie.title }}</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Release year:</th>
        <th>Casting:</th>
        <th>Directors:</th>
        <th>Producers:</th>
        
    </tr>
    <tr>
        <td>{{ movie.title }}</td>
        <td>{{ movie.release_year }}</td>
        <td>    
            {% for cast in movie.casting.all %}
                <p>{{ cast.first_name }} {{ cast.last_name }}</a></p> 
            {% endfor %}
        </td>
        <td>    
            {% for cast in movie.directors.all %}
                <p>{{ cast.first_name }} {{ cast.last_name }}</a></p> 
            {% endfor %}
        </td>
        <td>    
            {% for cast in movie.producers.all %}
                <p>{{ cast.first_name }} {{ cast.last_name }}</a></p> 
            {% endfor %}
        </td>
    </tr>
</table>

<p>
    <a href="{% url "cine:list" %}">Regresar</a>
</p>

{% endblock %}

cine/templates/movies/movie_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cine/templates/movies/movie_list.html
{% extends 'base.html' %}
{% block content %}
<h3>Movies:</h3>
<p>
    <a href="{% url "cine:new" %}">Add Movie</a>
</p>
<ul>
    <table>
        <tr>
            <th>Title</th>
            <th>Release year:</th>
            <th>Actions</th>
          </tr>
          {% for movie in object_list %}
            <tr>
                <td>{{ movie.title }}</td>
                <td>{{ movie.release_year }}</td>
                <td>    
                    <a href="{% url "cine:detail" movie.id %}">Show</a> | 
                    <a href="{% url "cine:edit" movie.id %}">Edit</a> | 
                    <a href="{% url "cine:delete" movie.id %}">Delete</a> 
                </td>
            </tr>
          {% endfor %}
    </table>
</ul>
{% endblock %}

cine/templates/persons/person_confirmdelete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    Are you sure to delete the person: "{{ object }}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cine/templates/persons/person_detail.html
{% extends 'base.html' %}
{% block content %}
<h3>Person:  {{ person.first_name }}  {{ person.last_name }}</h3>
<table>
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Movies as an actor/actriz:</th>
        <th>Movies as a director:</th>
        <th>Movies as a producers:</th>
        
    </tr>
    <tr>
        <td>{{ person.first_name }}</td>
        <td>{{ person.last_name }}</td>
        <td>
            {% for mov in person.movies_as_char.all %}
                <p>{{ mov.title }}</a></p> 
            {% endfor %}
        </td>
        <td>
            {% for mov in person.movies_as_dir.all %}
                <p>{{ mov.title }}</a></p> 
            {% endfor %}
        </td>
        <td>
            {% for mov in person.movies_as_prod.all %}
                <p>{{ mov.title }}</a></p> 
            {% endfor %}
        </td>
    </tr>
</table>

<p>
    <a href="{% url "cine:list" %}">Regresar</a>
</p>

{% endblock %}

cine/templates/persons/person_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cine/templates/persons/person_list.html
{% extends 'base.html' %}
{% block content %}


<h3>Persons:</h3>

<p>
    <a href="{% url "cine:new_p" %}">Add Person</a>
</p>

<ul>

    <table>
        <tr>
            <th>First name:</th>
            <th>Last name:</th>
            <th>Aliases:</th>
            <th>Actions</th>
          </tr>
          {% for person in object_list %}
            <tr>
                <td>{{ person.first_name }}</td>
                <td>{{ person.last_name }}</td>
                <td>
                {% if person.aliases %}
                    {{ person.aliases }}
                {% endif %}
                    </td>
                <td>
                    <a href="{% url "cine:detail_p" person.id %}">Show</a> | 
                    <a href="{% url "cine:edit_p" person.id %}">Edit</a> | 
                    <a href="{% url "cine:delete_p" person.id %}">Delete</a> 
                </td>
        
            </tr>
          {% endfor %}
    </table>

</ul>

{% endblock %}